package co.com.lulobank.exceptions;

public class EmpleadoException extends AssertionError{
    public static final String NO_COINCIDENCIA = "La informaci√≥n encontrada: %s, no es la esperada";

    public EmpleadoException(String message, Throwable cause) {
        super(message, cause);
    }
}
